version: '3.8'

services:
  spotify-player:
    build: .
    container_name: spotify-kids-player
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Mount config directory for persistence
      - ./config:/app/config
      - spotify-cache:/app/cache
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SPOTIFY_CONFIG_DIR=/app/config
      - SESSION_SECRET=${SESSION_SECRET:-spotify-kids-secret-change-me}
      - TZ=${TZ:-America/Los_Angeles}
    networks:
      - spotify-net
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx for SSL termination
  nginx:
    image: nginx:alpine
    container_name: spotify-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - spotify-player
    networks:
      - spotify-net

volumes:
  spotify-cache:
    driver: local

networks:
  spotify-net:
    driver: bridge